version: '3'
services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
     - type: bind
       source: /etc/letsencrypt
       target: /etc/letsencrypt
     - type: bind
       source: ./client/NodeBoard.conf
       target: /etc/nginx/conf.d/default.conf
     


  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3040:3040"
    environment:
      - NODE_ENV=development
    volumes: 
      - type: bind
        source: ./ImageUpload
        target: /app/server/ImageUpload
     